#!/usr/bin/env bash
MYDIR=$(dirname ${BASH_SOURCE})
docker build -t aas-rstudio ${MYDIR}

: ${NOTEBOOK_DIR:="${HOME}/notebooks"}
docker run --rm -d -v ${NOTEBOOK_DIR}:/home/rstudio/Documents -e DISABLE_AUTH=true -p 8787:8787 aas-rstudio
open http://localhost:8787
